apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: wpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: dhungelajay324/nginx:v3
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: wpapp
spec:
  selector:
    app: nginx-proxy
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
